// VUE/aprendiendo_vue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.imagen" :alt="pelicula.titulo" />
    </div>

    <h2>{{pelicula.titulo}}</h2>
    <span
      class="date"
      v-bind:class="{
            yeargreen: pelicula.year >=2015,
            yearred: pelicula.year >=2019
            }
            "
    >{{pelicula.year}}</span>
    <a href="#">Leer más</a>

    <input type="button" value="Marcar como favorita" 
      @click="marcarFAV(pelicula)"
    />
    

    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods:{
    marcarFAV(pelicula){
      this.$emit('favorita', pelicula);
    }
  }
};
</script>

// ANGULAR/aprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output , EventEmitter} from '@angular/core';
import { Pelicula } from '../../models/pelicula';


@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() peliculaItem : Pelicula ;
  @Output() marcarFav = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event,pelicula){
      this.marcarFav.emit({
        pelicula: pelicula
      });
  }

}

<article class="article-item" >
    <div class="image-wrap">
        <img src="{{peliculaItem.image}}" alt="{{peliculaItem.title}}" />
    </div>

    <h2>{{peliculaItem.title}}</h2>

    <span class="year" [ngClass]="{
                        'year-green' : peliculaItem.year >= 2018,
                        'year-red'  : peliculaItem.year < 2018 
               } ">
        {{peliculaItem.year}}
    </span>
    <button (click) = 'seleccionar($event,peliculaItem)'> 
        Favorita
    </button>

    <div class="clearfix"></div>
</article>
