// VUE/aprendiendo_vue/src/components/Articles.vue
<template>
  <div id="articles">
    <!--Listado articulos-->
    <div id="articles" v-if="articles && articles.length >= 1">
      <article class="article-item" v-for="article in articles" :key="article._id">
        <div class="image-wrap">
          <img :src="url+'get-image/'+article.image" :alt="article.title" v-if="article.image" />
          <img src="../assets/images/default.jpg" :alt="article.title" v-if="!article.image" />
        </div>

        <h2>{{article.title}}</h2>
        <span class="date">{{article.date | moment("from", "now")}}</span>
        <Router-link :to="{name:'article', params:{id:article._id}}">Leer más</Router-link>

        <div class="clearfix"></div>
      </article>
    </div>
    <div id="articles" v-else-if="articles && articles.length < 1">No existen artículos</div>
    <div v-else> Cargando ...</div>
  </div>
</template>

<script>
import Global from "../Global.js";

export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url
    };
  }
};
</script>

// REACT/AprendiendoReact/src/components/Articles.js
import React, { Component } from 'react';
import Moment from 'react-moment';
import 'moment/locale/es';


import {Link} from 'react-router-dom';

import imagedefault from '../assets/images/default.jpg';

import Global from '../Global'
import axios from 'axios'



class Articles extends Component {

    url = Global.url;

    state = {
        articles: {},
        status: null
    }

    

    componentWillMount() {

        var ultimosArticulos = this.props.ultimosArticulos;
        var search = this.props.search;

        //this.returnArticles(ultimosArticulos,search); 
        
            if(ultimosArticulos === "true"){
                this.getLastArticles();
            }else if(search && search !== "" && search !== undefined){
                this.getArticlesSearch(search);
            }else{
                this.getArticles();
            }
    
        
    };

    getLastArticles = () => {
        axios.get(this.url + "articles/last")
            .then(res => {
                this.setState({
                    articles: res.data.articles,
                    status: 'success'
                })
            })
            .catch(err => {
                this.setState({
                    articles:{},
                    status: 'success'
                });
            });
    }

    
    
    getArticlesSearch = (searched) => {
        axios.get(this.url + "search/" + searched)
            .then(res => {
                    this.setState({
                        articles: res.data.articles,
                        status: 'success'
                    })
                
            })
            .catch(err => {
                this.setState({
                    articles:[],
                    status: 'success'
                });
            });
            
    }


    getArticles = () => {
        axios.get(this.url + "articles")
            .then(res => {
                this.setState({
                    articles: res.data.articles,
                    status: 'success'
                })
            })
    }

    render() {

        
        if (this.state.articles.length >= 1) {

            var listArticles = this.state.articles.map((article) => {
                return (
                    <article key={article._id} className="article-item" id="article-template" >
                        <div className="image-wrap">
                            {article.image === null ? (
                                <img src={imagedefault} alt={article.title} />
                            ) : (
                                <img src={this.url + 'get-image/' + article.image} alt={article.title} />
                                )

                            }

                        </div>

                        <h2>{article.title}</h2>
                        <span className="date">
                            <Moment locale="es" fromNow>{article.date}</Moment>
                        </span>
                        <Link to={"/blog/article/"+article._id} >Leer mas</Link>

                        <div className="clearfix"></div>
                    </article>
                )


            });

            return (
                <div id="articles">
                    {listArticles}
                </div>
            );


        } else if (this.state.articles.length === 0 && this.state.status === 'success') {
            return (
                <div id="articles">
                    <h2 className="subheader">No hay Articulos</h2>
                </div>
            )
        } else {
            return (
                <div id="articles">
                    <h2 className="subheader">Cargando...</h2>
                </div>
            )
        }


    }

}

export default Articles;
