// VUE/aprendiendo_vue/src/components/Home.vue
<template>
  <div id="home">
    <Slider
      titulo="Bienvenido al sitio Web de Borja Martín creado con Vue"
      ShowBtn="blog"
      estilo="big"
    ></Slider>
    <div class="center">
      <div id="content">
        <LastArticles></LastArticles>
      </div>
    </div>
    <Sidebar></Sidebar>
  </div>
</template>

<script>
import LastArticles from "./LastArticles.vue";
import Sidebar from "./Sidebar.vue";
import Slider from "./Slider.vue";

export default {
  name: "Home",
  components: {
    LastArticles,
    Sidebar,
    Slider
  }
};
</script>

// REACT/AprendiendoReact/src/components/Home.js
import React, { Component } from 'react';

import Slider from './Slider';
import Sidebar from './Sidebar';
import Articles from './Articles';

class Home extends Component {

    render() {
        return (
            <div id="home">
                <Slider
                    title="Bienvenido al Curso de React con Víctor Robles de victorroblesweb.es"
                    siex="slider-big"
                    btn="Blog" 
                    enlace="/blog"
                    />
                <div className="center">
                    <div id="content">
                        <h1>Últimos articulos</h1>
                        <Articles ultimosArticulos="true"></Articles>
                    </div>
                    <Sidebar 
                        blog="true"
                        search="false"
                    />
                </div>
            </div>
        );
    }
}

export default Home;
