// VUE/aprendiendo_vue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.imagen" :alt="pelicula.titulo" />
    </div>

    <h2>{{pelicula.titulo}}</h2>
    <span
      class="date"
      v-bind:class="{
            yeargreen: pelicula.year >=2015,
            yearred: pelicula.year >=2019
            }
            "
    >{{pelicula.year}}</span>
    <a href="#">Leer más</a>

    <input type="button" value="Marcar como favorita" 
      @click="marcarFAV(pelicula)"
    />
    

    <div class="clearfix"></div>
  </article>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods:{
    marcarFAV(pelicula){
      this.$emit('favorita', pelicula);
    }
  }
};
</script>

// REACT/AprendiendoReact/src/components/Pelicula.js
import React, { Component } from 'react';

//class Pelicula extends Component {

class Pelicula extends Component {

    marcar = () => {
        this.props.marcarFAV(this.props.pelicula, this.props.indice);
    }

    render() {
        const {titulo,imagen} = this.props.pelicula;


        return (

            <article id="article-template" className="article-item">
                <div className="image-wrap">
                    <img src={imagen} alt={titulo} />
                </div>

                <h2>{titulo}</h2>
                <span className="date">
                    Hace 5 minutos
                        </span>
                <a href="infopelicula.html">Leer más</a>
                
                <button onClick={this.marcar}> Favorita </button>
                
                <div className="clearfix"></div>
            </article>

        );

    };


}

export default Pelicula;
