// VUE/aprendiendo_vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <Router-link to="/crearArticulo" class="btn btn-success">Crear artículo</Router-link>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas</p>
      <form @submit.prevent="goSearch">
        <input type="text" name="search" v-model="busqueda" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
  data(){
    return {
      busqueda:null
    }
  },
  methods:{
    goSearch(){
        this.$router.push('/redirect/'+ this.busqueda);
    }
  }
};
//<Router-link :to="{name:'search', params:{searchString:busqueda}}"><input type="submit" name="submit" value="Buscar" class="btn" /></Router-link>
</script>

// ANGULAR/aprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params} from '@angular/router';


@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchString: string;

  constructor(
    private _route: ActivatedRoute,
    private _router: Router
  ) { }

  ngOnInit(): void {
  }

  goSearch(){
    this._router.navigate(['/buscar/'+this.searchString]);
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear artículo</a>
    </div>

    <div id="search" class="sidebar-item">
            <h3>Buscador</h3>
            <p>Encuentra el artículo que buscas</p>
            <form #searchForm="ngForm" (ngSubmit)="goSearch()"  > 
                <input type="text" name="search"  #search="ngModel" [(ngModel)]="searchString" />
                <input type="submit" name="submit" value="Buscar" class="btn" />
            </form>
    </div>
</aside>

<div class="clearfix"></div>
