// REACT/AprendiendoReact/src/components/Peliculas.js
import React, { Component } from 'react';
import Pelicula from './Pelicula';
import Slider from './Slider';
import Sidebar from './Sidebar';

class Peliculas extends Component {

    state = {
        peliculas: [
            { titulo: 'Batman Begin', imagen: 'https://images-na.ssl-images-amazon.com/images/I/71BTH8VUA7L._SY445_.jpg' },
            { titulo: 'Gran Torino', imagen: 'https://images-na.ssl-images-amazon.com/images/I/91cpBX3kNrL._SL1500_.jpg' },
            { titulo: 'Looper', imagen: 'https://images-na.ssl-images-amazon.com/images/I/71YHgMctCEL._SL1000_.jpg' }
        ],
        nombre: 'Borja Martín',
        favorita: ''

    };

    cambiarTitulo = () => {

        var { peliculas } = this.state;
        peliculas[0].titulo = "Batman"

        this.setState({
            peliculas: peliculas
        })
    }

    favorita = (pelicula, indice) => {
        this.setState({
            favorita: pelicula,
            indice: indice
        })
    }


    render() {

        var pStyle = {
            background: 'green',
            color: 'white',
            padding: '10px'
        }

        return (

            <div id="peliculas">
                <Slider
                    title="Peliculas"
                    size="slider-small"
                />
                <div className="center">
                    <section id="content" className="Peliculas">
                        <h2 className="subheader">Listado de Peliculas</h2>
                        <p>Selección de peliculas de {this.state.nombre}</p>
                        <p> <button onClick={this.cambiarTitulo}> cambiar Titulo</button></p>

                        {this.state.favorita.titulo &&
                            <p className="favorita" style={pStyle} >
                                <strong>La Pelicula Favorita es: </strong>
                                <span>{this.state.indice}. {this.state.favorita.titulo}</span>
                            </p>
                        }

                        <div id="articles" className="peliculas">
                            {
                                this.state.peliculas.map((pelicula, i) => {
                                    return (
                                        <Pelicula
                                            key={i}
                                            pelicula={pelicula}
                                            indice={i}
                                            marcarFAV={this.favorita} />
                                    )
                                })
                            }


                        </div>

                    </section>
                    <Sidebar
                        blog="false"
                        search="true"
                    />
                    <div className="clearfix"></div>
                </div>
            </div>
        );
    }
}

export default Peliculas;

// VUE/aprendiendo_vue/src/components/Peliculas.vue
<template>
  <div id="Peliculas">
    <Slider titulo="Listado de peliculas" estilo="small"></Slider>
    <section id="content">
      <h1 class="subheader">Artículos</h1>
      <h1>{{misDatos | mayusculas}}</h1>
      
      <div class="favorita" v-if="pelifavorita">
        
        <h2>{{pelifavorita.titulo}}</h2>
      </div>
      <!--Listado articulos-->
      <div id="articles">
        <div v-for="pelicula in peliculasMayus" v-bind:key="pelicula.titulo">
          <Pelicula 
            :pelicula="pelicula"
            v-on:favorita="peliculaFavorita(pelicula)"
          ></Pelicula>
        </div>
        <!--AÑADIR ARTICULOS VIA JS-->
      </div>
    </section>
  </div>
</template>

<script>
import Pelicula from "./Pelicula.vue";
import Slider from "./Slider.vue";

export default {
  name: "Peliculas",
  components: {
    Pelicula,
    Slider
  },
  methods:{
      peliculaFavorita(favorita){
        this.pelifavorita=favorita;
      }
  },
  computed: {
    peliculasMayus(){
      var peliculasMod = this.peliculas;
      console.log(peliculasMod);
      for(var i=0; i < peliculasMod.length ; i++){
        peliculasMod[i].titulo = peliculasMod[i].titulo.toUpperCase();
      }
      
      return peliculasMod;
    },
    misDatos(){
      return this.nombre + ' ' + this.apellidos 
    }
  },
  filters:{
    mayusculas(value){
      return value.toUpperCase();
    }
  },
  data() {
    return {
      nombre:'Borja',
      apellidos: 'Martin Calvo',
      pelifavorita: null ,
      peliculas: [
        {
          titulo: "Batman Begin",
          year: 2019,
          imagen:
            "https://images-na.ssl-images-amazon.com/images/I/71BTH8VUA7L._SY445_.jpg"
        },
        {
          titulo: "Gran Torino",
          year: 2015,
          imagen:
            "https://images-na.ssl-images-amazon.com/images/I/91cpBX3kNrL._SL1500_.jpg"
        },
        {
          titulo: "Looper",
          year: 2017,
          imagen:
            "https://images-na.ssl-images-amazon.com/images/I/71YHgMctCEL._SL1000_.jpg"
        }
      ]
    };
  }
};
</script>
