// REACT/AprendiendoReact/src/components/Sidebar.js
import React, { Component } from 'react';

import {Redirect, Link} from 'react-router-dom';

class Sidebar extends Component {

    searchRef = React.createRef();

    state = {
        search: "" ,
        redirect: false
    }

    buscar = (e) => {
        e.preventDefault();
        
        var busqueda = this.searchRef.current.value;

        this.setState({
            search: busqueda,
            redirect: true
        })
        
        console.log("Search2 " + this.state.search);
    }


    render() {

        if(this.state.redirect){
            return (
                <Redirect to={'/redirect/'+this.state.search}></Redirect>
            );
        }

        return (
            <aside id="sidebar">
                {this.props.blog === "true" &&
                    <div id="nav-blog" className="sidebar-item">
                        <h3>Puedes hacer esto</h3>
                        <Link to={'/blog/newArticle'} className="btn btn-success">Crear artículo</Link>
                    </div>
                }

                {this.props.search  === "true" &&
                    <div id="search" className="sidebar-item">
                        <h3>Buscador</h3>
                        <p>Encuentra el artículo que buscas</p>
                        <form onSubmit={this.buscar}>
                            <input type="text" name="search" ref={this.searchRef}/>
                                <input type="submit" name="submit" value="Buscar" className="btn"  />
                            
                        </form>
                    </div>
                }
            </aside>
        );
    }

}
export default Sidebar;

// VUE/aprendiendo_vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <Router-link to="/crearArticulo" class="btn btn-success">Crear artículo</Router-link>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas</p>
      <form @submit.prevent="goSearch">
        <input type="text" name="search" v-model="busqueda" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: "Sidebar",
  data(){
    return {
      busqueda:null
    }
  },
  methods:{
    goSearch(){
        this.$router.push('/redirect/'+ this.busqueda);
    }
  }
};
//<Router-link :to="{name:'search', params:{searchString:busqueda}}"><input type="submit" name="submit" value="Buscar" class="btn" /></Router-link>
</script>
