// REACT/AprendiendoReact/src/components/Slider.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Slider extends Component {
    render() {
        return (
            <div id="slider" className={this.props.size} >
                <h1>{this.props.title}</h1>
                { this.props.btn && this.props.enlace &&
                    <Link to={this.props.enlace} className="btn-white">{this.props.btn}</Link>
                }
                
            </div>
        );
    }

}
export default Slider;

// VUE/aprendiendo_vue/src/components/Slider.vue
<template>
  <div
    id="slider"
    v-bind:class="{
                        'slider-big': estilo==='big',
                        'slider-small': estilo==='small'
                        }
                        "
  >
    <h1>{{titulo}}</h1>
    <div id="enlace" v-if="ShowBtn">
      <router-link :to=ShowBtn class="btn-white">Ir al blog</router-link>
    </div>
  </div>
</template>

<script>
export default {
  name: "Slider",
  props: ["titulo", "ShowBtn", "estilo"]
};
</script>
