// VUE/aprendiendo_vue/src/components/Formulario.vue
<template>
  <div id="formulario">
    <h1 class="subheader">Formulario</h1>
    <div id="datosForm" v-if="user.nombre ">
      <p>
        <strong>Nombre :</strong>
        {{user.nombre}}
      </p>

      <p>
        <strong>Apellidos :</strong>
        {{user.apellidos}}
      </p>

      <p>
        <strong>Bio :</strong>
        <span style="white-space: pre-line;">{{user.bio}}</span>
      </p>

      <p>
        <strong>Genero :</strong>
        {{user.genero }}
      </p>
    </div>

    <form class="mid-form" @submit.prevent="checkForm">
      <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" v-model="user.nombre" />
        <div v-if="submited && !$v.user.nombre.required">Este campo es obligatorio</div>
        <div v-if="submited && !$v.user.nombre.minLength">Este campo es debe ser mayor de 2 caracteres</div>
      </div>

      <div class="form-group">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" v-model="user.apellidos" />
        <div v-if="submited && !$v.user.apellidos.required">Este campo es obligatorio</div>
        <div v-if="submited && !$v.user.apellidos.minLength">Este campo es debe ser mayor de 2 caracteres</div>
      </div>

      <div class="form-group">
        <label for="bio">Biografia</label>
        <textarea name="bio" v-model="user.bio"></textarea>
        <div v-if="submited && !$v.user.bio.required">Este campo es obligatorio</div>
        <div v-if="submited && !$v.user.bio.minLength">Este campo es debe ser mayor de 10 caracteres</div>
      </div>

      <div class="form-group radibuttons">
        <input type="radio" name="genero" value="hombre" v-model="user.genero " /> Hombre
        <input type="radio" name="genero" value="mujer" v-model="user.genero " /> Mujer
        <input type="radio" name="genero" value="otro" v-model="user.genero " /> Otro
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Enviar" class="btn btn-success" />
    </form>
  </div>
</template>

<script>
import { required, minLength } from "vuelidate/lib/validators";

export default {
  name: "Formulario",
  data() {
    return {
      submited: false,
      user: {
        nombre: "",
        apellidos: "",
        bio: "",
        genero: ""
      },
      errors: []
    };
  },
  validations: {
    user: {
      nombre: {
        required,
        minLength: minLength(2)
      },
      apellidos: {
        required,
        minLength: minLength(2)
      },
      bio: {
        required,
        minLength: minLength(10)
      }
    }
  },
  methods: {
    checkForm() {
      this.submited = true;
      this.$v.$touch();
      console.log(this.$v.$invalid);
      if (this.$v.$invalid) {
        return false;
      }
      alert("Validación correcta");
      
    }
  }
};
</script>

// ANGULAR/aprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo:string;

  constructor() {
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    }
  }

  ngOnInit(): void {
  }

  onSubmit() {    
    //alert(JSON.stringify(this.user));
    console.log(this.user);
  }

  hasDadoCick(){
    //alert("Has pulsado Click");
  }

  hasSalido(){
    //alert("Has salido");
  }

  hasPulsadoEnter(){
    //alert("Has pulsado enter");
  }
}

<app-slider [nombre]="'Formulario'"  [size]="'small'">
</app-slider>

<div class="center">

    <section id="content">

        <h1 class="subheader">Formulario</h1>
        <!--
        <div id="datos-al-vuelo" *ngIf="user.nombre">
            <h2 class="subheader">Datos al vuelo</h2>
            <ul>
                <li>
                    {{user.nombre}}
                </li>
                <li>
                    {{user.apellidos}}
                </li>
                <li>
                    {{user.bio}}
                </li>
                <li>
                    {{user.genero}}
                </li>

            </ul>
        </div>
        -->
        <form class="mid-form" #userForm="ngForm" (ngSubmit) = "onSubmit()"> 
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" 
                    required pattern="[a-zA-Z]+"/>
                <small *ngIf="!nombre.valid && nombre.touched">
                    Nombre no es válido
                </small>
            </div>

            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required/>
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Apellidos no es válido
                </small>
            </div>

            <div class="form-group">
                <label for="bio">Biografia</label>
                <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required ></textarea>
                <small *ngIf="!bio.valid && bio.touched">
                    Bio no es válida
                </small>
            </div>

            <div class="form-group radibuttons">
                <input type="radio" name="genero" value="hombre" #genero="ngModel"  [(ngModel)]="user.genero" required/> Hombre
                <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" /> Mujer
                <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.genero" /> Otro
                <small *ngIf="!genero.valid && genero.touched">
                    Genero no es válida
                </small>
            </div>

            <div class="clearfix"></div>

            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid" />

        </form>

        <h2 class="subheader">Eventos</h2>
        <button (click)="hasDadoCick()">DaleClick</button>
        <input type="text" [(ngModel)]="campo" (blur)="hasSalido()" (keyup.enter)="hasPulsadoEnter()" />
        {{campo}}

    </section>

    <app-sidebar> </app-sidebar>
</div>
